[package]
name = "file-sync-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
md5 = "0.7.0"
rand = "0.8.5"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.217"
serde_json = "1.0.137"
